version: "3"
services:
  app_react:
    build: .
    container_name: app_react
    volumes:
      - build_react:/var/www/html
    env_file:
      - .env

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react

volumes:
  build_react:
